 name: Deploy MaritimeAgencies-Front UAT Service

 on:
   push:
     branches:
       - uat

 jobs:
   build:

     runs-on: ubuntu-latest
     env:
       target: '/var/www/html/MaritimeAgencies-Front/uat' # Enclose target path in single quotes
       message: "[${{ github.event.head_commit.committer.name }}](https://github.com/${{github.event.head_commit.committer.username}}) pushed new commit: \n`[ ${{github.event.head_commit.message}} ]` \nto [${{ github.event.repository.name }}](https://github.com/${{github.event.repository.html_url}}) UAT branch \nYou can now use it at https://uat.sinbad-iq.com"

     strategy:
       matrix:
         node-version: [18.x]

     steps:

      - name: Checkout code
        uses: actions/checkout@v2.4.2      

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: yarn

      - name: Build application
        run: yarn run build

      - name: Copy repository contents to remote server via scp
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.SSH_HOST }}
           port: 22
           username: ${{ secrets.SSH_USERNAME }}
           password: ${{ secrets.SSH_PASSWORD }}
           source: "./dist/"
           target: ${{ env.target }}
           debug: true # Enable debugging


      - name: send notification upload done to group
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELE_GROUP_ID  }}
            token: ${{ secrets.TELE_AUTH_TOKEN }}
            message: ${{ env.message }}
    
      - name: send notification upload done to group digital
        uses: appleboy/telegram-action@master
        with:
             to: ${{ secrets.TELE_GROUP_ID_DIJITAL  }}
             # to: 872819018
             token: ${{ secrets.TELE_AUTH_TOKEN }}
             message: ${{ env.message }}
             format: markdown
#             disable_web_page_preview: true

